version: '3.5'

services:
  user-database:
    build: ./databases/users
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: Backoffice
      MYSQL_USER: MainUser
      MYSQL_PASSWORD: MainPassword
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume: