version: '3.5'

services:
  user-database:
    build: ./databases/users
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: Backoffice
      MYSQL_USER: MainUser
      MYSQL_PASSWORD: MainPassword
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - micro-lab-network

  user-app:
    build: ./apps/users-microservice
    depends_on:
      - user-database
    ports:
      - "3000:3000"
    networks:
      - micro-lab-network

volumes:
  db-volume:

networks:
  micro-lab-network:
    driver: bridge