version: '3.5'

services:
  micro-lab-db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - micro-lab-network

  micro-lab-app-user:
    build: ./apps/users-microservice
    depends_on:
      - micro-lab-db
    ports:
      - "3000:3000"
    networks:
      - micro-lab-network

volumes:
  db-volume:

networks:
  micro-lab-network:
    driver: bridge