apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    home.lab: micro-lab-db
  name: micro-lab-db
spec:
  replicas: 1
  selector:
    matchLabels:
      home.lab: micro-lab-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        home.lab/micro-lab-network: "true"
        home.lab: micro-lab-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: Backoffice
            - name: MYSQL_PASSWORD
              value: MainPassword
            - name: MYSQL_ROOT_PASSWORD
              value: RootPassword
            - name: MYSQL_USER
              value: MainUser
          image: claudiojunior/microlab-db
          imagePullPolicy: IfNotPresent
          name: micro-lab-db
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "0.5"
              memory: 200M
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-volume
      restartPolicy: Always
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-volume
status: {}
