apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    home.lab: user-app
  name: user-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50