apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    home.lab: user-database
  name: user-database
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    home.lab: user-database
status:
  loadBalancer: {}
