apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: micro-lab-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              home.lab/micro-lab-network: "true"
  podSelector:
    matchLabels:
      home.lab/micro-lab-network: "true"
